CREATE DATABASE IF NOT EXISTS avatar;

USE avatar;

DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS `user`(
    `username` VARCHAR(30) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `password` VARCHAR(30) NOT NULL
)ENGINE = InnoDB;
