<script type='text/javascript' src='glge/src/core/glge_math.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_event.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_quicknote.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_animatable.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_document.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_placeable.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_jsonloader.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_group.js'></script> 
        <script type='text/javascript' src='glge/src/core/glge_messages.js'></script> 
        <script type='text/javascript' src='glge/src/animation/glge_action.js'></script> 
        <script type='text/javascript' src='glge/src/animation/glge_actionchannel.js'></script> 
        <script type='text/javascript' src='glge/src/animation/glge_animationcurve.js'></script> 
        <script type='text/javascript' src='glge/src/animation/glge_animationvector.js'></script> 
        <script type='text/javascript' src='glge/src/animation/glge_animationpoints.js'></script> 
        <script type='text/javascript' src='glge/src/geometry/glge_mesh.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_material.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_materiallayer.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_multimaterial.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_texture.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_texturecamera.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_texturecanvas.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_texturecube.js'></script> 
        <script type='text/javascript' src='glge/src/material/glge_texturevideo.js'></script> 
        <script type='text/javascript' src='glge/src/renderable/glge_lod.js'></script> 
        <script type='text/javascript' src='glge/src/renderable/glge_object.js'></script> 
        <script type='text/javascript' src='glge/src/renderable/glge_text.js'></script> 
        <script type='text/javascript' src='glge/src/renders/glge_renderer.js'></script> 
        <script type='text/javascript' src='glge/src/scene/glge_camera.js'></script> 
        <script type='text/javascript' src='glge/src/scene/glge_light.js'></script> 
        <script type='text/javascript' src='glge/src/scene/glge_scene.js'></script> 
        <script type='text/javascript' src='glge/src/extra/glge_particles.js'></script> 
        <script type='text/javascript' src='glge/src/extra/glge_filter2d.js'></script> 
        <script type='text/javascript' src='glge/src/extra/filters/glge_filter_glow.js'></script> 
        <script type='text/javascript' src='glge/src/extra/filters/glge_filter_ao.js'></script> 
        <script type='text/javascript' src='glge/src/extra/glge_collada.js'></script> 
        <script type='text/javascript' src='glge/src/extra/glge_input.js'></script> 
        <script type='text/javascript' src='glge/src/extra/glge_wavefront.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsext.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsabstract.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsbox.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsmesh.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsplane.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicssphere.js'></script> 
        <script type='text/javascript' src='glge/src/physics/glge_physicsconstraintpoint.js'></script> 

        <!-- jQuery --> 
        <script type='text/javascript' src='js/jquery-1.6.1.js'></script> 

        <!-- "Settings" --> 
        <script type='text/javascript'>
            url_to_static = 'models/aula_v7_base.dae';
            websocket_host = 'playsign.fi';
            websocket_port = '9999';
        </script>

        <script type='text/javascript' src='js/global.js'></script>
        <script type='text/javascript' src='js/3d.js'></script>
        <script type='text/javascript' src='js/entities.js'></script>
        <script type='text/javascript' src='js/socket.js'></script>
